# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
es:
  languageCode: es
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/es

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: content/en
#  title: English website title...
#  params:
#    description: Site description in English...
  menu:
    main:
      - name: About me
        url: '#about'
        weight: 10
      - name: Skills
        url: '#skills'
        weight: 20
      - name: Experience
        url: '#experience'
        weight: 30
      - name: Publications
        url: '#publications'
        weight: 40
      - name: Contact
        url: '#contact'
        weight: 50

fr:
  languageCode: fr
  contentDir: content/fr
  menu:
    main:
      - name: À propos de moi
        url: '#about'
        weight: 10
      - name: Skills
        url: '#skills'
        weight: 20
      - name: Expérience
        url: '#experience'
        weight: 30
      - name: Publications
        url: '#publications'
        weight: 40
      - name: Contact
        url: '#contact'
        weight: 50
